FROM alpine:latest

ARG APPLICATION=android-studio-3.0.0
ARG DOWNLOAD_URL=https://dl.google.com/dl/android/studio/ide-zips/3.0.0.18/android-studio-ide-171.4408382-linux.zip

ARG INSTALL_DIRECTORY_PREFIX=/opt
ARG DESKTOP_ENTRY_PREFIX=/usr/share/applications/${APPLICATION}

ENV INSTALL_DIRECTORY=${INSTALL_DIRECTORY_PREFIX}/${APPLICATION} \
    DESKTOP_ENTRY=${DESKTOP_ENTRY_PREFIX}/androidstudio.desktop

## Add application
RUN mkdir -p $INSTALL_DIRECTORY_PREFIX \
    && apk add --no-cache --virtual .download-deps wget ca-certificates unzip \
    && wget -nv -O android-studio.zip $DOWNLOAD_URL \
    && unzip -q android-studio.zip \
    && rm -f android-studio.zip \
    && mv android-studio $INSTALL_DIRECTORY \
    && apk del .download-deps

## Add desctop entry
RUN mkdir -p $DESKTOP_ENTRY_PREFIX \
    && { echo "[Desktop Entry]" \
         && echo "Type=Application" \
         && echo "Exec=${INSTALL_DIRECTORY}/bin/studio.sh" \
         && echo "Name=${APPLICATION}" \
         && echo "Icon=${INSTALL_DIRECTORY}/bin/studio.png"; \
       } > $DESKTOP_ENTRY

VOLUME ["$INSTALL_DIRECTORY", "$DESKTOP_ENTRY_PREFIX"]

CMD ["true"]
