FROM alpine:latest

ARG APPLICATION=VSCode-1.17.2-amd64
ARG DOWNLOAD_URL=https://az764295.vo.msecnd.net/stable/b813d12980308015bcd2b3a2f6efa5c810c33ba5/code-stable-code_1.17.2-1508162334_amd64.tar.gz

ARG INSTALL_DIRECTORY_PREFIX=/opt
ARG DESKTOP_ENTRY_PREFIX=/usr/share/applications/${APPLICATION}

ENV INSTALL_DIRECTORY=${INSTALL_DIRECTORY_PREFIX}/${APPLICATION} \
    DESKTOP_ENTRY=${DESKTOP_ENTRY_PREFIX}/vscode.desktop

## Add application
RUN mkdir -p $INSTALL_DIRECTORY_PREFIX \
    && apk add --no-cache --virtual .download-deps wget ca-certificates \
    && wget -nv -O vscode.tar.gz $DOWNLOAD_URL \
    && tar xfz vscode.tar.gz \
    && mv VSCode-linux-x64 $INSTALL_DIRECTORY \
    && rm -f vscode.tar.gz \
    && apk del .download-deps

## Add desctop entry
RUN mkdir -p $DESKTOP_ENTRY_PREFIX \
    && { echo "[Desktop Entry]" \
         && echo "Type=Application" \
         && echo "Exec=${INSTALL_DIRECTORY}/bin/code" \
         && echo "Name=${APPLICATION}" \
         && echo "Icon=${INSTALL_DIRECTORY}/resources/app/resources/linux/code.png"; \
       } > $DESKTOP_ENTRY

VOLUME ["$INSTALL_DIRECTORY", "$DESKTOP_ENTRY_PREFIX"]

CMD ["true"]
