FROM alpine:latest

ARG APPLICATION=pycharm-community-2017.2.3
ARG DOWNLOAD_URL=https://download.jetbrains.com/python/pycharm-community-2017.2.3.tar.gz

ARG INSTALL_DIRECTORY_PREFIX=/opt
ARG DESKTOP_ENTRY_PREFIX=/usr/share/applications/${APPLICATION}

ENV INSTALL_DIRECTORY=${INSTALL_DIRECTORY_PREFIX}/${APPLICATION} \
    DESKTOP_ENTRY=${DESKTOP_ENTRY_PREFIX}/pycharm.desktop

## Add application
RUN mkdir -p $INSTALL_DIRECTORY_PREFIX \
    && apk add --no-cache --virtual .download-deps wget ca-certificates \
    && wget -nv -O pycharm.tar.gz $DOWNLOAD_URL \
    && tar xfz pycharm.tar.gz -C $INSTALL_DIRECTORY_PREFIX \
    && rm -f pycharm.tar.gz \
    && apk del .download-deps

## Add desktop entry
RUN mkdir -p $DESKTOP_ENTRY_PREFIX \
    && { echo "[Desktop Entry]" \
         && echo "Type=Application" \
         && echo "Exec=${INSTALL_DIRECTORY}/bin/pycharm.sh" \
         && echo "Name=${APPLICATION}" \
         && echo "Icon=${INSTALL_DIRECTORY}/bin/pycharm.png"; \
       } > $DESKTOP_ENTRY

VOLUME ["$INSTALL_DIRECTORY", "$DESKTOP_ENTRY_PREFIX"]

CMD ["true"]
