FROM alpine:latest

ARG APPLICATION=atom-1.21.1-amd64
ARG DOWNLOAD_URL=https://github.com/atom/atom/releases/download/v1.21.1/atom-amd64.tar.gz

ARG INSTALL_DIRECTORY_PREFIX=/opt
ARG DESKTOP_ENTRY_PREFIX=/usr/share/applications/${APPLICATION}

ENV INSTALL_DIRECTORY=${INSTALL_DIRECTORY_PREFIX}/${APPLICATION} \
    DESKTOP_ENTRY=${DESKTOP_ENTRY_PREFIX}/atom.desktop

## Add application
RUN mkdir -p $INSTALL_DIRECTORY_PREFIX \
    && apk add --no-cache --virtual .download-deps wget ca-certificates \
    && wget -nv -O atom.tar.gz $DOWNLOAD_URL \
    && tar xfz atom.tar.gz -C $INSTALL_DIRECTORY_PREFIX \
    && rm -f atom.tar.gz \
    && apk del .download-deps

## Add desctop entry
RUN mkdir -p $DESKTOP_ENTRY_PREFIX \
    && { echo "[Desktop Entry]" \
         && echo "Type=Application" \
         && echo "Exec=${INSTALL_DIRECTORY}/atom" \
         && echo "Name=${APPLICATION}" \
         && echo "Icon=${INSTALL_DIRECTORY}/atom.png"; \
       } > $DESKTOP_ENTRY

VOLUME ["$INSTALL_DIRECTORY", "$DESKTOP_ENTRY_PREFIX"]

CMD ["true"]
